- name: configuring mysql
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed
  - name: start and enabled service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: connect to mysql
    community.mysql.mysql_db:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.devaws.fun
    register: mysql_info
  - name: print the output
    ansible.builtin.debug:
      msg: "mysql info: {{ mysql_info }}""    